# CONJUNTO DE EJERCICIOS

**1.Encuentre las primeras dos iteraciones del método de Jacobi para los siguientes sistemas lineales, por
medio de 𝐱(𝟎) = 0:**

In [13]:
import numpy as np

def jacobi(A, b, x0, iteraciones):
    n = len(A)
    x = x0.copy()
    for it in range(iteraciones):
        x_new = np.zeros_like(x)
        for i in range(n):
            s1 = sum(A[i][j] * x[j] for j in range(i))
            s2 = sum(A[i][j] * x[j] for j in range(i + 1, n))
            x_new[i] = (b[i] - s1 - s2) / A[i][i]
        x = x_new
        print(f"Iteración {it + 1}: {x}")
    return x

# Ejercicio 1a
A1a = np.array([[3, -1, 1], [3, 6, 2], [3, 3, 7]], dtype=np.float32)
b1a = np.array([1, 0, 4], dtype=np.float32)
x0 = np.zeros(len(b1a))
print("Ejercicio 1a:")
jacobi(A1a, b1a, x0, 2)

# Ejercicio 1b
A1b = np.array([[10, -1, 0], [-1, 10, -2], [0, -2, 10]], dtype=np.float32)
b1b = np.array([9, 7, 6], dtype=np.float32)
x0 = np.zeros(len(b1b))
print("Ejercicio 1b:")
jacobi(A1b, b1b, x0, 2)

# Ejercicio 1c
A1c = np.array([[10, 5, 0], [5, 10, -4], [-4, 8, -1]], dtype=np.float32)
b1c = np.array([6, 25, -11], dtype=np.float32)
x0 = np.zeros(len(b1c))
print("Ejercicio 1c:")
jacobi(A1c, b1c, x0, 2)

# Ejercicio 1d
A1d = np.array([
    [4, 1, 0, 1, 0], 
    [-1, 3, 1, 1, 0], 
    [2, 1, 5, 0, 1], 
    [1, 1, 3, 4, 1], 
    [2, 0, 1, 1, 4]
], dtype=np.float32)
b1d = np.array([6, 6, 6, 6, 6], dtype=np.float32)
x0 = np.zeros(len(b1d))
print("Ejercicio 1d:")
jacobi(A1d, b1d, x0, 2)


Ejercicio 1a:
Iteración 1: [0.33333333 0.         0.57142857]
Iteración 2: [ 0.14285714 -0.35714286  0.42857143]
Ejercicio 1b:
Iteración 1: [0.9 0.7 0.6]
Iteración 2: [0.97 0.91 0.74]
Ejercicio 1c:
Iteración 1: [ 0.6  2.5 11. ]
Iteración 2: [-0.65  6.6  28.6 ]
Ejercicio 1d:
Iteración 1: [1.5 2.  1.2 1.5 1.5]
Iteración 2: [ 0.625  1.6   -0.1   -0.65   0.075]


array([ 0.625,  1.6  , -0.1  , -0.65 ,  0.075])

**2.Repita el ejercicio 1 usando el método de Gauss-Siedel.**

In [14]:
def gauss_seidel(A, b, x0, iteraciones):
    n = len(A)
    x = x0.copy()
    for it in range(iteraciones):
        for i in range(n):
            s1 = sum(A[i][j] * x[j] for j in range(i))
            s2 = sum(A[i][j] * x[j] for j in range(i + 1, n))
            x[i] = (b[i] - s1 - s2) / A[i][i]
        print(f"Iteración {it + 1}: {x}")
    return x

# Ejercicio 2a
gauss_seidel(A1a, b1a, x0, 2)

# Ejercicio 2b
gauss_seidel(A1b, b1b, x0, 2)

# Ejercicio 2c
gauss_seidel(A1c, b1c, x0, 2)

# Ejercicio 2d
gauss_seidel(A1d, b1d, x0, 2)


Iteración 1: [ 0.33333333 -0.16666667  0.5         0.          0.        ]
Iteración 2: [ 0.11111111 -0.22222222  0.61904762  0.          0.        ]
Iteración 1: [0.9   0.79  0.758 0.    0.   ]
Iteración 2: [0.979  0.9495 0.7899 0.     0.    ]
Iteración 1: [ 0.6  2.2 26.2  0.   0. ]
Iteración 2: [ -0.5   13.23 118.84   0.     0.  ]
Iteración 1: [1.5     2.5     0.1     0.425   0.61875]
Iteración 2: [0.76875    2.08125    0.3525     0.3684375  0.93539062]


array([0.76875   , 2.08125   , 0.3525    , 0.3684375 , 0.93539062])

**3.Utilice el método de Jacobi para resolver los sistemas lineales en el ejercicio 1, con TOL = 10-3.**

In [6]:
import numpy as np

def jacobi_tol(A, b, x0, tol, max_iter=30):
    n = len(A)
    x = x0.copy()
    x_new = x0.copy()
    it = 0
    while it < max_iter:
        it += 1
        for i in range(n):
            s1 = sum(A[i][j] * x[j] for j in range(i))
            s2 = sum(A[i][j] * x[j] for j in range(i + 1, n))
            x_new[i] = (b[i] - s1 - s2) / A[i][i]
        if np.allclose(x, x_new, atol=tol):
            break
        x = x_new.copy()
        print(f"Iteración {it}: {x}")
    return x

# Resolver sistemas del ejercicio 1 con TOL = 10^{-3} y un máximo de 30 iteraciones
tol = 1e-3
jacobi_tol(A1a, b1a, x0, tol)
jacobi_tol(A1b, b1b, x0, tol)
jacobi_tol(A1c, b1c, x0, tol)
jacobi_tol(A1d, b1d, x0, tol)


Iteración 1: [1.  1.4 1. ]
Iteración 2: [0.15 0.6  0.2 ]
Iteración 3: [0.75 1.27 0.75]
Iteración 4: [0.3075     0.8        0.32666667]
Iteración 5: [0.63666667 1.15016667 0.63083333]
Iteración 6: [0.39704167 0.89183333 0.40438889]
Iteración 7: [0.57484722 1.08089722 0.570375  ]
Iteración 8: [0.44458819 0.94101667 0.44808519]
Iteración 9: [0.54070324 1.04363005 0.53813171]
Iteración 10: [0.47002663 0.96795171 0.4718889 ]
Iteración 11: [0.52206762 1.02360624 0.52067389]
Iteración 12: [0.4837615  0.98262465 0.48477538]
Iteración 13: [0.51195615 1.01278803 0.51120462]
Iteración 14: [0.49120069 0.99058539 0.49175194]
Iteración 15: [0.50647768 1.0069292  0.50607131]
Iteración 16: [0.49523205 0.99489913 0.49553104]
Iteración 17: [0.5035097  1.00375456 0.50328961]
Iteración 18: [0.49741655 0.99723626 0.49757858]
Iteración 19: [0.50190165 1.00203435 0.5017824 ]
Iteración 20: [0.49860021 0.99850253 0.498688  ]
Iteración 21: [0.50103037 1.00110227 0.50096575]
Iteración 22: [0.49924156 0.99918863 

IndexError: index 3 is out of bounds for axis 0 with size 3

**4.Utilice el método de Gauss-Siedel para resolver los sistemas lineales en el ejercicio 1, con TOL = 10-3.**

In [7]:
import numpy as np

def gauss_seidel_tol(A, b, x0, tol, max_iter=30):
    n = len(A)
    x = x0.copy()
    it = 0
    while it < max_iter:
        it += 1
        x_old = x.copy()
        for i in range(n):
            s1 = sum(A[i][j] * x[j] for j in range(i))
            s2 = sum(A[i][j] * x_old[j] for j in range(i + 1, n))
            x[i] = (b[i] - s1 - s2) / A[i][i]
        if np.allclose(x, x_old, atol=tol):
            break
        print(f"Iteración {it}: {x}")
    return x

# Resolver sistemas del ejercicio 1 con TOL = 10^{-3} y un máximo de 30 iteraciones
tol = 1e-3
gauss_seidel_tol(A1a, b1a, x0, tol)
gauss_seidel_tol(A1b, b1b, x0, tol)
gauss_seidel_tol(A1c, b1c, x0, tol)
gauss_seidel_tol(A1d, b1d, x0, tol)



Iteración 1: [1.  0.8 0.4]
Iteración 2: [0.6  0.96 0.48]
Iteración 3: [0.52  0.992 0.496]
Iteración 4: [0.504  0.9984 0.4992]
Iteración 5: [0.5008  0.99968 0.49984]
Iteración 1: [0.9   0.79  0.758]
Iteración 2: [0.979  0.9495 0.7899]
Iteración 3: [0.99495  0.957475 0.791495]
Iteración 1: [ 0.6  2.2 26.2]
Iteración 2: [ -0.5   13.23 118.84]
Iteración 3: [ -6.015   53.0435 459.408 ]
Iteración 4: [ -25.92175   199.224075 1708.4796  ]
Iteración 5: [ -99.0120375   735.39785875 6290.23102   ]
Iteración 6: [ -367.09892938  2702.14187269 23096.530699  ]
Iteración 7: [-1350.47093634  9916.34774777 84743.66572755]
Iteración 8: [ -4957.57387389  36378.75322796 310871.32131925]
Iteración 9: [ -18188.77661398  133445.41683469 1140329.44113344]
Iteración 10: [ -66722.10841734  489495.33066205 4182862.07896578]
Iteración 11: [ -244747.06533102  1795520.86425182 15343166.17533869]
Iteración 12: [ -897759.83212591  6586148.88619843 56280241.41809111]
Iteración 13: [-3.29307384e+06  2.41586360e+07  2.06

IndexError: index 3 is out of bounds for axis 0 with size 3

**5.El sistema lineal**

In [ ]:
import numpy as np

def jacobi(A, b, x0, iteraciones):
    n = len(A)
    x = x0.copy()
    for it in range(iteraciones):
        x_new = np.zeros_like(x)
        for i in range(n):
            s1 = sum(A[i][j] * x[j] for j in range(i))
            s2 = sum(A[i][j] * x[j] for j in range(i + 1, n))
            x_new[i] = (b[i] - s1 - s2) / A[i][i]
        x = x_new
        print(f"Iteración {it + 1}: {x}")
    return x

A = np.array([[2, -1, 1], [2, 2, 2], [-1, -1, 2]], dtype=np.float32)
b = np.array([-1, 4, -5], dtype=np.float32)
x0 = np.zeros(len(b))

print("Método de Jacobi:")
jacobi(A, b, x0, 25)


Método de Jacobi:
Iteración 1: [-0.5  2.  -2.5]
Iteración 2: [ 1.75  5.   -1.75]
Iteración 3: [2.875 2.    0.875]
Iteración 4: [ 0.0625 -1.75   -0.0625]
Iteración 5: [-1.34375  2.      -3.34375]
Iteración 6: [ 2.171875  6.6875   -2.171875]
Iteración 7: [3.9296875 2.        1.9296875]
Iteración 8: [-0.46484375 -3.859375    0.46484375]
Iteración 9: [-2.66210938  2.         -4.66210938]
Iteración 10: [ 2.83105469  9.32421875 -2.83105469]
Iteración 11: [5.57763672 2.         3.57763672]
Iteración 12: [-1.28881836 -7.15527344  1.28881836]
Iteración 13: [-4.7220459  2.        -6.7220459]
Iteración 14: [ 3.86102295 13.4440918  -3.86102295]
Iteración 15: [8.15255737 2.         6.15255737]
Iteración 16: [ -2.57627869 -12.30511475   2.57627869]
Iteración 17: [-7.94069672  2.         -9.94069672]
Iteración 18: [ 5.47034836 19.88139343 -5.47034836]
Iteración 19: [12.1758709  2.        10.1758709]
Iteración 20: [ -4.58793545 -20.35174179   4.58793545]
Iteración 21: [-12.96983862   2.         -14.96

array([-20.82787284,   2.        , -22.82787284])

**6.El sistema lineal**

In [ ]:
def gauss_seidel(A, b, x0, tol, max_iter):
    n = len(A)
    x = x0.copy()
    for it in range(max_iter):
        x_new = x.copy()
        for i in range(n):
            s1 = sum(A[i][j] * x_new[j] for j in range(i))
            s2 = sum(A[i][j] * x[j] for j in range(i + 1, n))
            x_new[i] = (b[i] - s1 - s2) / A[i][i]
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            print(f"Convergencia alcanzada en iteración {it + 1}")
            break
        x = x_new
        print(f"Iteración {it + 1}: {x}")
    return x

x0 = np.zeros(len(b))
tol = 1e-5
max_iter = 100

print("Método de Gauss-Seidel:")
gauss_seidel(A, b, x0, tol, max_iter)


Método de Gauss-Seidel:
Iteración 1: [-0.5  2.5 -1.5]
Iteración 2: [ 1.5   2.   -0.75]
Iteración 3: [ 0.875  1.875 -1.125]
Iteración 4: [ 1.      2.125  -0.9375]
Iteración 5: [ 1.03125  1.90625 -1.03125]
Iteración 6: [ 0.96875   2.0625   -0.984375]
Iteración 7: [ 1.0234375  1.9609375 -1.0078125]
Iteración 8: [ 0.984375    2.0234375  -0.99609375]
Iteración 9: [ 1.00976562  1.98632812 -1.00195312]
Iteración 10: [ 0.99414062  2.0078125  -0.99902344]
Iteración 11: [ 1.00341797  1.99560547 -1.00048828]
Iteración 12: [ 0.99804688  2.00244141 -0.99975586]
Iteración 13: [ 1.00109863  1.99865723 -1.00012207]
Iteración 14: [ 0.99938965  2.00073242 -0.99993896]
Iteración 15: [ 1.00033569  1.99960327 -1.00003052]
Iteración 16: [ 0.99981689  2.00021362 -0.99998474]
Iteración 17: [ 1.00009918  1.99988556 -1.00000763]
Iteración 18: [ 0.99994659  2.00006104 -0.99999619]
Iteración 19: [ 1.00002861  1.99996758 -1.00000191]
Iteración 20: [ 0.99998474  2.00001717 -0.99999905]
Iteración 21: [ 1.00000811  1

array([ 0.99999571,  2.00000477, -0.99999976])

In [ ]:
import numpy as np

def gauss_seidel(A, b, x0, tol, max_iter):
    n = len(A)
    x = x0.copy()
    for it in range(max_iter):
        x_new = x.copy()
        for i in range(n):
            s1 = sum(A[i][j] * x_new[j] for j in range(i))
            s2 = sum(A[i][j] * x[j] for j in range(i + 1, n))
            x_new[i] = (b[i] - s1 - s2) / A[i][i]
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            print(f"Convergencia alcanzada en iteración {it + 1}")
            break
        x = x_new
        print(f"Iteración {it + 1}: {x}")
    return x

A = np.array([[1, 0, -1], [-0.5, 1, -0.25], [1, -0.5, 1]], dtype=np.float32)
b = np.array([0.2, -1.425, 2], dtype=np.float32)
x0 = np.zeros(len(b))
tol = 1e-5
max_iter = 300

print("Método de Gauss-Seidel:")
solution = gauss_seidel(A, b, x0, tol, max_iter)
print(f"Solución aproximada: {solution}")


Método de Gauss-Seidel:
Iteración 1: [ 0.2        -1.32499995  1.13750002]
Iteración 2: [ 1.33750002 -0.47187493  0.42656251]
Iteración 3: [ 0.62656251 -1.00507807  0.87089845]
Iteración 4: [ 1.07089846 -0.67182611  0.59318849]
Iteración 5: [ 0.79318849 -0.88010858  0.76675722]
Iteración 6: [ 0.96675722 -0.74993204  0.65827676]
Iteración 7: [ 0.85827676 -0.83129238  0.72607705]
Iteración 8: [ 0.92607705 -0.78044217  0.68370187]
Iteración 9: [ 0.88370187 -0.81222355  0.71018635]
Iteración 10: [ 0.91018636 -0.79236019  0.69363355]
Iteración 11: [ 0.89363355 -0.80477479  0.70397905]
Iteración 12: [ 0.90397906 -0.79701566  0.69751311]
Iteración 13: [ 0.89751312 -0.80186512  0.70155433]
Iteración 14: [ 0.90155433 -0.79883421  0.69902857]
Iteración 15: [ 0.89902857 -0.80072852  0.70060717]
Iteración 16: [ 0.90060717 -0.79954458  0.69962054]
Iteración 17: [ 0.89962055 -0.80028454  0.70023718]
Iteración 18: [ 0.90023719 -0.79982206  0.69985178]
Iteración 19: [ 0.89985179 -0.80011111  0.7000926

In [ ]:
        for i in range(n):
            s1 = sum(A[i][j] * x_new[j] for j in range(i))
            s2 = sum(A[i][j] * x[j] for j in range(i + 1, n))
            x_new[i] = (b[i] - s1 - s2) / A[i][i]
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            print(f"Convergencia alcanzada en iteración {it + 1}")
            break
        x = x_new
        print(f"Iteración {it + 1}: {x}")
    return x

A = np.array([[1, 0, -1], [-0.5, 1, -0.25], [1, -0.5, 1]], dtype=np.float32)
b = np.array([0.2, -1.425, 2], dtype=np.float32)
x0 = np.zeros(len(b))
tol = 1e-5
max_iter = 300

print("Método de Gauss-Seidel:")
solution = gauss_seidel(A, b, x0, tol, max_iter)
print(f"Solución aproximada: {solution}")


In [ ]:
b_nuevo = np.array([0.3, -1.5, 2.1], dtype=np.float32)

print("Método de Gauss-Seidel con sistema cambiado:")
solution_nuevo = gauss_seidel(A, b_nuevo, x0, tol, max_iter)
print(f"Solución aproximada con sistema cambiado: {solution_nuevo}")


Método de Gauss-Seidel con sistema cambiado:
Iteración 1: [ 0.30000001 -1.34999999  1.1249999 ]
Iteración 2: [ 1.42499991 -0.50625007  0.42187496]
Iteración 3: [ 0.72187497 -1.03359377  0.86132805]
Iteración 4: [ 1.16132806 -0.70400396  0.58666987]
Iteración 5: [ 0.88666988 -0.90999759  0.75833123]
Iteración 6: [ 1.05833124 -0.78125157  0.65104288]
Iteración 7: [ 0.95104289 -0.86171784  0.7180981 ]
Iteración 8: [ 1.01809811 -0.81142642  0.67618859]
Iteración 9: [ 0.9761886  -0.84285856  0.70238203]
Iteración 10: [ 1.00238204 -0.82321347  0.68601113]
Iteración 11: [ 0.98601114 -0.83549165  0.69624294]
Iteración 12: [ 0.99624295 -0.82781779  0.68984806]
Iteración 13: [ 0.98984807 -0.83261395  0.69384486]
Iteración 14: [ 0.99384487 -0.82961635  0.69134686]
Iteración 15: [ 0.99134687 -0.83148985  0.69290811]
Iteración 16: [ 0.99290812 -0.83031891  0.69193233]
Iteración 17: [ 0.99193234 -0.83105075  0.69254219]
Iteración 18: [ 0.9925422  -0.83059335  0.69216103]
Iteración 19: [ 0.99216104 -

***8.Un cable coaxial está formado por un conductor interno de 0.1 pulgadas cuadradas y un conductor externo de 0.5 pulgadas cuadradas. El potencial en un punto en la sección transversal del cable se describe
mediante la ecuación de Laplace.**
a.
¿La matriz es estrictamente diagonalmente dominante?
b.
Resuelva el sistema lineal usando el método de Jacobi con x(0) = 0 y TOL = 10-2.
c.
Repita la parte b) mediante el método de Gauss-Siedel.

In [ ]:
import numpy as np

def jacobi(A, b, x0, tol, max_iter):
    n = len(A)
    x = x0.copy()
    for it in range(max_iter):
        x_new = np.zeros_like(x)
        for i in range(n):
            s1 = sum(A[i][j] * x[j] for j in range(i))
            s2 = sum(A[i][j] * x[j] for j in range(i + 1, n))
            x_new[i] = (b[i] - s1 - s2) / A[i][i]
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            print(f"Convergencia alcanzada en iteración {it + 1}")
            break
        x = x_new
        print(f"Iteración {it + 1}: {x}")
    return x

def gauss_seidel(A, b, x0, tol, max_iter):
    n = len(A)
    x = x0.copy()
    for it in range(max_iter):
        x_new = x.copy()
        for i in range(n):
            s1 = sum(A[i][j] * x_new[j] for j in range(i))
            s2 = sum(A[i][j] * x[j] for j in range(i + 1, n))
            x_new[i] = (b[i] - s1 - s2) / A[i][i]
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            print(f"Convergencia alcanzada en iteración {it + 1}")
            break
        x = x_new
        print(f"Iteración {it + 1}: {x}")
    return x

# Datos de la matriz y el vector b proporcionados en el problema
A = np.array([
    [ 4, -1,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0],
    [-1,  4, -1,  0,  0,  0,  0, -1,  0,  0,  0,  0],
    [ 0, -1,  4, -1,  0,  0,  0,  0, -1,  0,  0,  0],
    [ 0,  0, -1,  4, -1,  0,  0,  0,  0, -1,  0,  0],
    [ 0,  0,  0, -1,  4, -1,  0,  0,  0,  0, -1,  0],
    [ 0,  0,  0,  0, -1,  4,  0,  0,  0,  0,  0, -1],
    [-1,  0,  0,  0,  0,  0,  4, -1,  0,  0,  0,  0],
    [ 0, -1,  0,  0,  0,  0, -1,  4, -1,  0,  0,  0],
    [ 0,  0, -1,  0,  0,  0,  0, -1,  4, -1,  0,  0],
    [ 0,  0,  0, -1,  0,  0,  0,  0, -1,  4, -1,  0],
    [ 0,  0,  0,  0, -1,  0,  0,  0,  0, -1,  4, -1],
    [ 0,  0,  0,  0,  0, -1,  0,  0,  0,  0, -1,  4]
], dtype=np.float32)

b = np.array([220, 110, 110, 110, 110, 110, 110, 110, 110, 110, 110, 220], dtype=np.float32)
x0 = np.zeros(len(b), dtype=np.float32)
tol = 1e-5
max_iter = 300

print("Método de Jacobi:")
solution_jacobi = jacobi(A, b, x0, tol, max_iter)
print(f"Solución aproximada con Jacobi: {solution_jacobi}\n")

print("Método de Gauss-Seidel:")
solution_gauss_seidel = gauss_seidel(A, b, x0, tol, max_iter)
print(f"Solución aproximada con Gauss-Seidel: {solution_gauss_seidel}")


Método de Jacobi:
Iteración 1: [55.  27.5 27.5 27.5 27.5 27.5 27.5 27.5 27.5 27.5 27.5 55. ]
Iteración 2: [68.75  55.    48.125 48.125 48.125 48.125 48.125 48.125 48.125 48.125
 55.    68.75 ]
Iteración 3: [80.78125 68.75    65.3125  63.59375 65.3125  56.71875 56.71875 65.3125
 63.59375 65.3125  68.75    80.78125]
Iteración 4: [86.36719  80.35156  76.484375 76.484375 74.765625 64.02344  64.02344
 74.765625 76.484375 76.484375 80.35156  86.36719 ]
Iteración 5: [91.09375 86.9043  85.83008 84.43359 82.71484 67.7832  67.7832  82.71484
 84.43359 85.83008 86.9043  91.09375]
Iteración 6: [93.671875 92.40967  91.44287  91.09375  87.28027  70.95215  70.95215
 87.28027  91.09375  91.44287  92.40967  93.671875]
Iteración 7: [95.840454 95.598755 96.14929  95.041504 91.11389  72.73804  72.73804
 91.11389  95.041504 96.14929  95.598755 95.840454]
Iteración 8: [97.0842   98.27591  98.92044  98.35312  93.344574 74.23859  74.23859
 93.344574 98.35312  98.92044  98.27591  97.0842  ]
Iteración 9: [ 98.12